---
- name: Include Initial playbook
  import_playbook: initial.yml
- name: Include NFS setup playbook
  import_playbook: nfs.yml
- name: Includes /etc/hosts setup playbook
  import_playbook: hosts.yml
- name: Include Python playbook
  import_playbook: python.yml
## Seems clang is needed for Rust
- name: Include Clang Install playbook
  import_playbook: clang.yml
- name: Include Rust Install playbook
  import_playbook: rust.yml
- name: Include ZSH Install playbook
  import_playbook: zsh.yml
