---
# Adapted from playbook found here and clang docs: https://github.com/loderunner/ansible-clang
# Clang apt install info here: https://apt.llvm.org/
- name: Install Clang LLVM compiler
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    - present_state: "present"
  tasks:
    - name: Add LLVM APT key
      become: "yes"
      apt_key:
        url: https://apt.llvm.org/llvm-snapshot.gpg.key
    - name: Add LLVM APT repository
      become: "yes"
      apt_repository:
        repo: deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy main
        update_cache: yes
    - name: Install a Clang 14
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - clang-14
        - lldb-14
        - lld-14
    - name: Install a Clang 14 Key Packages LLVM
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libllvm-14-ocaml-dev
        - libllvm14
        - llvm-14
        - llvm-14-dev
        - llvm-14-doc
        - llvm-14-examples
        - llvm-14-runtime
    - name: Install a Clang 14 Key Packages Clang and co
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - clang-14
        - clang-tools-14
        - clang-14-doc
        - libclang-common-14-dev
        - libclang-14-dev
        - libclang1-14
        - clang-format-14
        - python3-clang-14
        - clangd-14
        - clang-tidy-14
    - name: Install a Clang 14 Key Packages libfuzzer
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libfuzzer-14-dev
    - name: Install a Clang 14 Key Packages libfuzzer
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - lldb-14
    - name: Install a Clang 14 Key Packages lld (linker)
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - lld-14
    - name: Install a Clang 14 Key Packages libc++
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libc++-14-dev
        - libc++abi-14-dev
    - name: Install a Clang 14 Key Packages OpenMP
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libomp-14-dev
    - name: Install a Clang 14 Key Packages libclc, libunwind-14-dev, mlir
      become: "yes"
      apt:
        name: "{{ packages }}"
        update_cache: "yes"
        state: "{{ present_state }}"
      vars:
        packages:
        - libclc-14-dev
        - libunwind-14-dev
        - libmlir-14-dev
        - mlir-14-tools

- name: Export LLVM_CONFIG on Primary Node's bashrc for ansible_ssh_user
  connection: ssh
  gather_facts: "no"
  hosts: gcp_primary
  tasks:
    - name: Ensure export of llvm-config PATH
      # become: "yes"
      lineinfile:
        dest: "/home/{{ ansible_ssh_user }}/.bashrc"
        line: 'export LLVM_CONFIG=/usr/bin/llvm-config-14'
